language: android

notifications:
email: false  

components:

    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - tools
    # - platform-tools
    - tools
    # The BuildTools version used by your project
    - build-tools-25.0.3
    - platform-tools
    - extra-android-m2repository
    - extra-google-android-suppo

    # The SDK version used to compile your project
    - android-16
    - android-21
    - android-22
    - android-25

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-19

    # Specify at least one system image,
     #if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-16
    - sys-img-armeabi-v7a-android-21
    - sys-img-armeabi-v7a-android-22
    - sys-img-armeabi-v7a-android-25
    
jdk: oraclejdk8
